name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Backend dependencies
        working-directory: ./Backend
        run: npm install

      - name: Install Frontend dependencies
        working-directory: ./Frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./Frontend
        run: npm run build

        

      - name: Deploy to Vercel
        working-directory: ./Frontend
        run: npx vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }} --project-id=${{ secrets.VERCEL_PROJECT_ID }}



      